CREATE GLOBAL TEMPORARY TABLE "VPLANADM"."GET_LR_TRUNK_EXHAUST_DATA" 

   (
   "TRUNK_ID"  NUMBER, 
   "REGION" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(10 BYTE), 
	"LATA" VARCHAR2(18 BYTE), 
	"LINK_TYPE" VARCHAR2(18 BYTE), 
	"A_DEVICE" VARCHAR2(16 BYTE), 
	"Z_DEVICE" VARCHAR2(16 BYTE), 
	"LINK_NAME" VARCHAR2(40 BYTE), 
  "TOTAL_TRUNK_BW"  NUMBER, 
  "PORT_SPEED"  NUMBER, 
  "Switch" VARCHAR2(16 BYTE),
  "Slot" VARCHAR2(5 BYTE),
  "Sub_Slot" VARCHAR2(5 BYTE),
  "Max_In_Out_BW" VARCHAR2(12 BYTE),
  "Avg_BW" VARCHAR2(12 BYTE),
  "Port" VARCHAR2(5 BYTE),
  "day_count" NUMBER, 
  "AVERAGE_PEAK_UTIL" NUMBER(10,5), 
	"TRUNK_NAME" VARCHAR2(60 BYTE), 
	"PORT_NAME" VARCHAR2(60 BYTE), 
  "TRUNK" VARCHAR2(60 BYTE), 
	"MAX_IN_OUT" NUMBER(10,5), 
	"AVG_UTIL" NUMBER(10,5),
  "WRR26WEEK" NUMBER(10,5),
  "WRRDEFINED" NUMBER(10,5),
	"T2E26WEEKDATE" VARCHAR2(32 BYTE), 
	"T2EDEFINEDDATE" VARCHAR2(32 BYTE), 
	"UNIQUE_ID" NUMBER
   ) ON COMMIT PRESERVE ROWS 
  TABLESPACE "VPGTT_TEMP_DATA14" ;
